workflows:
  ios:
    name: iOS CI
    environment:
      vars:
        LANG: en_US.UTF-8
    scripts:
      - name: Update RubyGems and Install CocoaPods
        script: |
          gem update --system
          gem install cocoapods
          pod install
      - name: Build and test
        script: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 14' clean build test