workflows:
  ios:
    name: iOS CI
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          gem install cocoapods
          pod install
      - name: Build and test
        script: |
          xcodebuild -workspace YourApp.xcworkspace -scheme YourApp -sdk iphoneos -destination 'platform=iOS Simulator,name=iPhone 14' clean build test
    artifacts:
      - build/YourApp.ipa

